In [1]:
import os
import pandas as pd

In [2]:
emission = pd.read_csv (r"C:\Users\mhtaba\Desktop\pod_lca_git\pod_lca\data\transportation_dataset\Emission.csv")
data_material = pd.read_csv (r"C:\Users\mhtaba\Desktop\pod_lca_git\pod_lca\data\transportation_dataset\EC3 Category to CFS Group mapping.csv")
cfs = pd.read_csv (r"C:\Users\mhtaba\Desktop\pod_lca_git\pod_lca\data\transportation_dataset\cfs_2017.csv")

In [3]:
data_material

             material  SCTG
0      FireSprinklers    409
1      SmokeDetectors    409
2                AHUs    344
3                RTUs    344
4        AirTerminals    344
..                ...    ...
234          Profiles    409
235  CleaningProducts    233
236          Clothing    303
237      FoodBeverage      7
238              Zinc    324

[239 rows x 2 columns]

In [4]:
sctg = data_material[data_material["material"] == "StructuralSteel"].iloc[0,1]
sctg = int(str(sctg)[:2])
sctg

32

In [5]:
df = cfs[cfs ["SCTG"] == "32"]
df

,SHIPMT_ID,ORIG_STATE,ORIG_MA,ORIG_CFS_AREA,DEST_STATE,DEST_MA,DEST_CFS_AREA,NAICS,QUARTER,SCTG,MODE,SHIPMT_VALUE,SHIPMT_WGHT,SHIPMT_DIST_GC,SHIPMT_DIST_ROUTED,TEMP_CNTL_YN,EXPORT_YN,EXPORT_CNTRY,HAZMAT,WGT_FACTOR
19,20,17,176,17-176,27,378,27-378,332,2,32,4,58828,25033,348,406,N,N,N,N,99.8
23,24,1,99999,01-99999,47,99999,47-99999,4235,3,32,4,19000,42222,102,136,N,N,N,N,341.7
44,45,20,312,20-312,29,312,29-312,332,2,32,5,736,1307,15,16,N,N,N,N,1102.1
55,56,48,288,48-288,48,206,48-206,332,1,32,4,13122,6424,197,220,N,N,N,N,212.9
105,106,12,422,12-422,12,370,12-370,4235,2,32,5,22980,12132,186,220,N,N,N,N,443.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048410,1048411,12,422,12-422,51,40060,51-40060,4239,2,32,4,32719,38689,635,710,N,N,N,N,18.6
1048467,1048468,36,408,36-408,36,408,36-408,331,4,32,5,9839,21866,2,3,N,N,N,N,20.8
1048472,1048473,19,99999,19-99999,17,99999,17-99999,4235,2,32,4,2023,2326,91,116,N,N,N,N,131.4
1048491,1048492,18,258,18-258,48,206,48-206,331,3,32,15,12264,45849,882,1190,N,N,N,N,508.3
1048570,1048571,40,538,40-538,40,416,40-416,4235,1,32,4,1380,3702,108,117,N,N,N,N,556.1

In [6]:
quartiles = df["SHIPMT_DIST_ROUTED"].quantile([0.25, 0.5, 0.75]).values

In [7]:
quartiles

array([ 27., 142., 498.])

In [8]:
def assign_quartile(x, q1, q2, q3):

    if x <= q1:
        return 'Q1'
    elif x <= q2:
        return 'Q2'
    elif x <= q3:
        return 'Q3'
    else:
        return 'Q4'

df['quartile'] = df["SHIPMT_DIST_ROUTED"].apply(assign_quartile, args=(quartiles[0], quartiles[1], quartiles[2]))

C:\Users\mhtaba\AppData\Local\Temp\ipykernel_7460\1949202098.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['quartile'] = df["SHIPMT_DIST_ROUTED"].apply(assign_quartile, args=(quartiles[0], quartiles[1], quartiles[2]))

In [9]:
local = df[df['quartile'] == 'Q1']
regional = df[df['quartile'] == 'Q2']
regional_c = df[df['quartile'] == 'Q3']
national = df[df['quartile'] == 'Q4']

In [10]:
local

,SHIPMT_ID,ORIG_STATE,ORIG_MA,ORIG_CFS_AREA,DEST_STATE,DEST_MA,DEST_CFS_AREA,NAICS,QUARTER,SCTG,...,SHIPMT_VALUE,SHIPMT_WGHT,SHIPMT_DIST_GC,SHIPMT_DIST_ROUTED,TEMP_CNTL_YN,EXPORT_YN,EXPORT_CNTRY,HAZMAT,WGT_FACTOR,quartile
44,45,20,312,20-312,29,312,29-312,332,2,32,...,736,1307,15,16,N,N,N,N,1102.1,Q1
106,107,6,99999,06-99999,6,99999,06-99999,4235,4,32,...,91,41,3,3,N,N,N,N,961.2,Q1
107,108,18,99999,18-99999,18,99999,18-99999,331,3,32,...,2771,1056,10,10,N,N,N,N,818.4,Q1
241,242,42,99999,42-99999,24,47900,24-47900,332,4,32,...,1674,440,22,25,N,N,N,N,661.4,Q1
267,268,41,440,41-440,41,440,41-440,4235,4,32,...,613,1578,19,23,N,N,N,N,279.9,Q1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1047898,1047899,28,99999,28-99999,28,99999,28-99999,4239,2,32,...,6498,39343,5,6,N,N,N,N,783.0,Q1
1047935,1047936,42,99999,42-99999,42,99999,42-99999,4233,4,32,...,419,23,4,6,N,N,N,N,3737.2,Q1
1048089,1048090,39,212,39-212,39,212,39-212,4235,2,32,...,248,57,5,5,N,N,N,N,596.8,Q1
1048283,1048284,6,99999,06-99999,6,99999,06-99999,4233,3,32,...,351,863,8,8,N,N,N,N,276.1,Q1
1048467,1048468,36,408,36-408,36,408,36-408,331,4,32,...,9839,21866,2,3,N,N,N,N,20.8,Q1

In [11]:
local_dis = local["SHIPMT_DIST_ROUTED"].mean()

In [12]:
local_dis

11.458078305644612

In [13]:
local = pd.merge (emission, local, on ="MODE")

In [24]:
local[local ["mode_name"] == "Truck"]

,mode_name,MODE,eff,Units,GWP,AP,EP,ODP,SFP,SHIPMT_ID,...,SHIPMT_VALUE,SHIPMT_WGHT,SHIPMT_DIST_GC,SHIPMT_DIST_ROUTED,TEMP_CNTL_YN,EXPORT_YN,EXPORT_CNTRY,HAZMAT,WGT_FACTOR,quartile
0,Truck,4,1,tkm,27,9,24,27,24,107,...,91,41,3,3,N,N,N,N,961.2,Q1
1,Truck,4,1,tkm,45,15,40,45,40,684,...,1285,525,5,5,N,N,N,N,9.5,Q1
2,Truck,4,1,tkm,234,78,208,234,208,882,...,3602,32422,22,26,N,N,N,N,130.6,Q1
3,Truck,4,1,tkm,9,3,8,9,8,988,...,7,11,1,1,N,N,N,N,1967.4,Q1
4,Truck,4,1,tkm,36,12,32,36,32,1496,...,2227,95,2,4,N,N,N,N,162.5,Q1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3935,Truck,4,1,tkm,225,75,200,225,200,1046754,...,2088,26739,22,25,N,N,N,N,52.3,Q1
3936,Truck,4,1,tkm,81,27,72,81,72,1047417,...,27,1,9,9,N,N,N,N,2932.1,Q1
3937,Truck,4,1,tkm,54,18,48,54,48,1047899,...,6498,39343,5,6,N,N,N,N,783.0,Q1
3938,Truck,4,1,tkm,45,15,40,45,40,1048090,...,248,57,5,5,N,N,N,N,596.8,Q1
3939,Truck,4,1,tkm,72,24,64,72,64,1048284,...,351,863,8,8,N,N,N,N,276.1,Q1

In [17]:
local.iloc[:,4:9]

       GWP  AP  EP  ODP  SFP
0        9   3   8    9    8
1        9   3   8    9    8
2        9   3   8    9    8
3        9   3   8    9    8
4        9   3   8    9    8
...    ...  ..  ..  ...  ...
15899    4  10   6    5    7
15900    4  10   6    5    7
15901    4  10   6    5    7
15902    4  10   6    5    7
15903    4  10   6    5    7

[15904 rows x 5 columns]

In [18]:
# impact_columns = ['GWP', 'AP', 'EP', 'ODP', 'SFP']

# Multiply each environmental impact by SHIPMT_DIST_ROUTED
local.iloc[:,4:9] = local.iloc[:,4:9].multiply(local['SHIPMT_DIST_ROUTED'], axis=0)

In [19]:
mean_impact = local.iloc[:,4:9].mean().to_dict()

mean_impact

{'GWP': 85.30118209255534,
 'AP': 55.34362424547284,
 'EP': 65.43699698189135,
 'ODP': 89.55011317907444,
 'SFP': 56.93913480885312}

In [2]:
fafa = pd.read_csv (r"C:\Users\mhtaba\Desktop\pod_lca_git\pod_lca\temp\transportation_dataset\FAF561.csv")

In [3]:
fafa.head()

,fr_orig,dms_orig,dms_dest,fr_dest,fr_inmode,dms_mode,fr_outmode,sctg2,trade_type,dist_band,...,tmiles_2020,tmiles_2021,tmiles_2022,tmiles_2023,tmiles_2025,tmiles_2030,tmiles_2035,tmiles_2040,tmiles_2045,tmiles_2050
0,NaN,11,11,NaN,NaN,1,NaN,1,1,1,...,3.375547,3.482383,3.502040,3.471863,4.364371,5.327137,6.342501,7.763605,9.571647,11.343818
1,NaN,11,19,NaN,NaN,1,NaN,1,1,2,...,51.005589,52.619906,52.916934,52.460954,62.052489,72.493059,82.113979,96.869428,116.602924,134.683927
2,NaN,11,129,NaN,NaN,1,NaN,1,1,3,...,0.472040,0.486980,0.489729,0.485509,0.486727,0.533539,0.564126,0.638719,0.750361,0.844720
3,NaN,11,131,NaN,NaN,1,NaN,1,1,2,...,2.283328,2.355595,2.368892,2.348480,2.549854,3.018065,3.155784,3.394250,3.850035,4.178881
4,NaN,11,139,NaN,NaN,1,NaN,1,1,2,...,1.337213,1.379536,1.387323,1.375368,1.554450,1.863748,1.969298,2.141527,2.456208,2.683008